### ISSUE TITLE
Does this FS support streaming?

### ISSUE THREAD

**Issue by philipp-spiess** [EtiennePerot/splitfs#1]
Question in title :)

**Comment by EtiennePerot** [comment]
Depends what you mean by "streaming".
- The "chunk up audio/video files and serve those chunks as separate adaptively-reencoded files" kind of streaming? No, as that requires knowledge as to how to re-encode each chunk.
- The "read a file in chunks as the underlying non-split file is being written to" kind of streaming? Probably, haven't tested that though.
- Something else?

**Comment by philipp-spiess** [comment]
Thank you for answering 👍
